# Generated by Django 6.0.5 on 2026-05-25 01:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_pasajeros',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='precio_total',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.tour'),
            preserve_default=False,
        ),
    ]
