name: Integracion y Despliegue Continuo

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesion en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir la imagen a Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: elifokami/turismo-backend:latest